# DOCS: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: ote ci
on: [pull_request, push]

jobs:


  check_release_notes:
    name: check_release_notes
    timeout-minutes: 2
    strategy:
      matrix:
        go-version: [1.16]
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: check if changes have release notes
        if: github.ref != 'refs/heads/master'
        env:
          GIT_BRANCH: ${{ github.ref }}
        run: |
          if [ "$GIT_BRANCH" == "master" ]
          then
              printf "\n $GIT_BRANCH branch, ignoring check for relese notes \n"
          elif [ "$GIT_BRANCH" == *"refs/tags/"* ]
          then
              printf "\n $GIT_BRANCH branch, ignoring check for relese notes \n"
          else
              ChangedFiles=`git diff --name-only origin/master`
              echo $ChangedFiles
              case "$ChangedFiles" in
                *CHANGELOG.*)
                    printf "\n Thanks, your commits include updates to release notes. \n";;
                *)
                    printf '\n You should add release notes to CHANGELOG.md \n' && exit 77;;
              esac
          fi

  run_tests:
    name: run_tests
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [1.16]
        platform: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: tests and benchmarks
        run: |
          go test -timeout 1m -race -run=XXXX -bench=. ./...
          go test -timeout 1m -v -race -cover -coverprofile=coverage.txt ./... && bash <(curl -s https://codecov.io/bash) -v
          go tool cover -html=coverage.txt -o coverage.html
          go tool cover -func=coverage.txt
        if: matrix.platform != 'windows-latest'

      - name: dummy run
        run: |
          go build -trimpath --race -o ote .
          ./ote -h
          ./ote -f testdata/mod1 -r

  run_analysis:
    name: run_analysis
    timeout-minutes: 2
    strategy:
      matrix:
        go-version: [1.16]
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: install apt and pip deps
        run: |
          pwd; ls -lsha
          sudo apt-get -y update
          sudo apt -y install wget

      - name: install tools
        run: |
          set -x
          go version
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/cmd/gosec@latest
          go install github.com/quasilyte/go-ruleguard/cmd/ruleguard@latest
          go install github.com/orijtech/structslop/cmd/structslop@latest
          go install github.com/orijtech/httperroryzer/cmd/httperroryzer@latest
          go install golang.org/x/tools/cmd/stress@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

          /home/runner/go/bin/staticcheck -version
        env:
          SOME_ENV_VAR: '2020.1.6'

      - name: static analysis
        run: |
          diff <(gofmt -d .) <(printf "")
          go vet -v -all ./...
          go vet -vettool=/home/runner/go/bin/shadow ./...
          /home/runner/go/bin/staticcheck -tests -show-ignored -go 1.16 ./...
          /home/runner/go/bin/gosec ./...
          /home/runner/go/bin/structslop ./...
          /home/runner/go/bin/httperroryzer ./...
          /home/runner/go/bin/golangci-lint run --no-config --enable=bodyclose,exhaustive,exhaustivestruct,exportloopref,gochecknoglobals,tparallel,unparam,wrapcheck ./...

          mkdir -p /tmp/dgryski/semgrep-go
          wget -nc --output-document=/tmp/dgryski/semgrep-go/rules.go https://raw.githubusercontent.com/dgryski/semgrep-go/master/ruleguard.rules.go
          go get github.com/quasilyte/go-ruleguard/dsl
          /home/runner/go/bin/ruleguard -c 1 -rules /tmp/dgryski/semgrep-go/rules.go ./...
          go mod tidy

          # deadlock detection
          # https://github.com/cockroachdb/cockroach/issues/7972
          go get github.com/sasha-s/go-deadlock
          find . -name "*.go" | xargs -n 1 sed -i.backup 's/sync.RWMutex/deadlock.RWMutex/'
          find . -name "*.go" | xargs -n 1 sed -i.backup 's/sync.Mutex/deadlock.Mutex/'
          find . -name '*.backup' -delete
          /home/runner/go/bin/goimports -w .
          go test -timeout 1m -v -race ./...
          go mod tidy

          # TODO: add https://github.com/system-pclub/GCatch

      - name: stress test
        run: |
          go test -o ote.test -c -race
          /home/runner/go/bin/stress -timeout 10s ./ote.test
